name: Employe Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: samin/mysql-action@v1
        with:
          mysql database: 'employannex'
          mysql root password: 'root'
          mysql user: 'root'
          mysql password: 'root'
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: SpringBoot Report               # Name of the folder
          path: target/           # Path to test results